# Generated by Django 4.2.7 on 2025-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('min_cibil_score', models.IntegerField()),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField()),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CibilPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('service_years', models.IntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desired_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('existing_loans', models.IntegerField()),
                ('predicted_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
